name: Pull and Push NGINX to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: devtechtransferacr01
  ACR_LOGIN_SERVER: devtechtransferacr01.azurecr.io
  IMAGE_NAME: nginx
  TAG: ${{ github.run_id }}

jobs:
  push-nginx:
    runs-on: azure-devdx-ubuntu-latest-2-core

    steps:
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Pull and Tag nginx image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push image to ACR
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
